import = [
    "~/.config/alacritty/color_scheme/gruvbox_material_hard_dark.toml",
    "~/.config/alacritty/font_face/jetbrains_mono.toml",
]


[env]
TERM = "xterm-256color"


[shell]
program = "/usr/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux"]


[window]
#decorations = "none"
dynamic_padding = true
padding.x = 4
padding.y = 4


[font]
size = 12


[cursor]
unfocused_hollow = false


[mouse]
bindings = [{ mouse = "Middle", action = "Paste" }]


[keyboard]
bindings = [
    { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
    { key = "V", mods = "Control|Shift", action = "Paste" },
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "Insert", mods = "Shift", action = "PasteSelection" },
    { key = "Key0", mods = "Control", action = "ResetFontSize" },
    { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
    { key = "Plus", mods = "Control", action = "IncreaseFontSize" },
    { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
    { key = "F11", mods = "None", action = "ToggleFullscreen" },
    { key = "Paste", mods = "None", action = "Paste" },
    { key = "Copy", mods = "None", action = "Copy" },
    { key = "PageUp", mods = "None", action = "ScrollPageUp" },
    { key = "PageDown", mods = "None", action = "ScrollPageDown" },
    { key = "Home", mods = "Shift", action = "ScrollToTop" },
    { key = "End", mods = "Shift", action = "ScrollToBottom" },
]
